<?php

/**
 * JobeetCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class JobeetCategory extends BaseJobeetCategory
{
  public function getActiveJobs($max = 10)
  {
    $q = $this->getActiveJobsQuery()
      ->limit($max);
   
    return $q->execute();
  }

  /**
   * Un ruta puede usar cualquier columna de su objeto asociado como parámetro. 
   * También puede usa cualquier otro valor si hay un método asociado definido 
   * en la clase del objeto. Debido a que el parámetro slug no tiene una columna
   * correspondiente en la tabla category, necesitamos agregar un método de 
   * acceso virtual en JobeetCategory para que la ruta funcione.
   * @return [String] [category name]
   */
  // slug es una columna real en la tabla JobeetCategory, es necesario eliminar 
  // el método getSlug()
  // public function getSlug()
  // {
  //   return Jobeet::slugify($this->getName());
  // }

  public function countActiveJobs()
  {
    return $this->getActiveJobsQuery()->count();
  }

  /**
   * El método sfDoctrinePager::setQuery() toma un objeto Doctrine_Query para 
   * utilizarlo a la hora de seleccionar los elementos de la base de datos.
   * @return [Doctrine_Query] [Doctrine_Query]
   */
  public function getActiveJobsQuery()
  {
    $q = Doctrine_Query::create()
      ->from('JobeetJob j')
      ->where('j.category_id = ?', $this->getId());
   
    return Doctrine_Core::getTable('JobeetJob')->addActiveJobsQuery($q);
  }
}