<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/08/30 00:31:00

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=test',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
